services:
  postgres:
    image: postgres:16
    container_name: postgres_db_bank
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./bank
      args:
        NTTDATA_BANK_DB_URL: ${NTTDATA_BANK_DB_URL}
        NTTDATA_BANK_DB_USERNAME: ${NTTDATA_BANK_DB_USERNAME}
        NTTDATA_BANK_DB_PASSWORD: ${NTTDATA_BANK_DB_PASSWORD}
    container_name: spring_backend_bank
    environment:
      NTTDATA_BANK_DB_URL: ${NTTDATA_BANK_DB_URL}
      NTTDATA_BANK_DB_USERNAME: ${NTTDATA_BANK_DB_USERNAME}
      NTTDATA_BANK_DB_PASSWORD: ${NTTDATA_BANK_DB_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./bank-frontend
      args:
        VITE_BANK_BACKEND_BASE_URL: ${VITE_BANK_BACKEND_BASE_URL}
    container_name: react_frontend_bank
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data: